nome = " DESAFIO 009 "
print('{:=^40}\n'.format(nome))

print('Vamos relembrar a Tabuada!')
numero = int(input('Escolha um número para vermos toda sua tabuada: '))
print('='*15)
print('{}  X  {} = {}'.format(numero, 1, numero*1))
print('{}  X  {} = {}'.format(numero, 2, numero*2))
print('{}  X  {} = {}'.format(numero, 3, numero*3))
print('{}  X  {} = {}'.format(numero, 4, numero*4))
print('{}  X  {} = {}'.format(numero, 5, numero*5))
print('{}  X  {} = {}'.format(numero, 6, numero*6))
print('{}  X  {} = {}'.format(numero, 7, numero*7))
print('{}  X  {} = {}'.format(numero, 8, numero*8))
print('{}  X  {} = {}'.format(numero, 9, numero*9))
print('{}  X {} = {}'.format(numero, 10, numero*10))
print('='*15)
